<?php echo $this->doctype(); ?>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle('zSportsCenter')->setSeparator(' - ')->setAutoEscape(false); ?>
		<?php echo $this->headMeta()
			->appendName('viewport', 'width=device-width, initial-scale=1.0')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		; ?>
		<!-- Le styles -->
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
			->prependStylesheet($this->basePath() . '/css/style.css')
			->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
			->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
		; ?>
		<!-- Scripts -->
		<?php echo $this->headScript()
			->prependFile($this->basePath() . '/js/bootstrap.min.js')
			->prependFile($this->basePath() . '/js/jquery.min.js')
			->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
			->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
		; ?>
	</head>
	
	<body>

	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			<a class="navbar-brand" href="<?php echo $this->url('home'); ?>">zSportsCenter</a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li class="active"><a href="<?php echo $this->url('home'); ?>">Home</a></li>
					<li><a href="<?php echo $this->url('home', array('action' => 'contact')); ?>">Contact</a></li>
					<li><a href="<?php echo $this->url('home', array('action' => 'admin')); ?>">Administration</a></li>
				</ul>
				
				<div class="navbar-right">
					<ul class="nav navbar-nav">
						<li><a href="<?php echo $this->url('home', array('action' => 'signup')); ?>">Sign up</a></li>
					</ul>
				</div>
				
				<form class="navbar-form navbar-right" method="post" action="<?php echo $this->url('home', array('action' => 'signin')); ?>">
					<div class="form-group">
						<input type="text" name="nickname" placeholder="Nickname" class="form-control">
					</div>
					<div class="form-group">
						<input type="password" name="password" placeholder="Password" class="form-control">
					</div>
					<button type="submit" class="btn btn-primary">Sign in</button>
				</form>
				
				<
				
			</div><!--/.nav-collapse -->
		</div>
	</div>
	
		<div class="container">
			<?php echo $this->content; ?>
			<hr />
			<footer>
				<p>&copy; 2010 - <?php echo date('Y') ?> by HE-Arc.</p>
			</footer>
		</div>
		<?php /* echo $this->inlineScript(); */ ?>
	</body>
</html>
