   <?php echo $this->doctype(); ?>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <?php echo $this->headTitle('zSportsCenter')->setSeparator(' - ')->setAutoEscape(false) ?>
      <?php echo $this->headMeta()
         ->appendName('viewport', 'width=device-width, initial-scale=1.0')
         ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
         ?>
      <!-- Le styles -->
      <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
         ->prependStylesheet($this->basePath() . '/css/style.css')
         ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
         ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
      <!-- Scripts -->
      <?php echo $this->headScript()
         ->prependFile($this->basePath() . '/js/bootstrap.min.js')
         ->prependFile($this->basePath() . '/js/jquery.min.js')
         ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
         ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
         ; ?>
   </head>
   <body>
      <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
         <div class="container">
            <div class="navbar-header">
               <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
               </button>
               <a class="navbar-brand" href="<?php echo $this->url('home') ?>">&nbsp;<?php echo $this->translate('zSportsCenter') ?></a>
            </div>
            <div class="collapse navbar-collapse">
               <ul class="nav navbar-nav">
                  <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Homepage') ?></a></li>
               </ul>
               <ul class="nav navbar-nav">
                  <li class="active"><a href="<?php echo $this->url('home', array('action' => 'Contact')) ?>"><?php echo $this->translate('Contact') ?></a></li>
               </ul>
                <ul class="nav navbar-nav">
                    <li class="active"><a href="<?php echo $this->url('home', array('action' => 'Admin')) ?>"><?php echo $this->translate('Admin') ?></a></li>
                </ul>
                 <ul class="nav navbar-nav navbar-right">
                    <li class="active"><a href="<?php echo $this->url('home', array('action' => 'Sign-up')) ?>"><?php echo $this->translate('Sign-up') ?></a></li>
                </ul>
                 <ul class="nav navbar-nav navbar-right">
                    <li class="active"><a href="<?php echo $this->url('home', array('action' => 'Sign-in')) ?>"><?php echo $this->translate('Sign-in') ?></a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <form class="navbar-form navbar-left" role="search">
                        <div class="form-group">
                            <input type="password" class="form-control" placeholder="Password">
                                </div>
                    </form></ul>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <form class="navbar-form navbar-left" role="search">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Login">
                                </div>
                    </form></ul>
                </ul>
            </div>
            <!--/.nav-collapse -->
         </div>
      </nav>
      <div class="container">
         <?php echo $this->content; ?>
         <script type="text/javascript">
            $(".commentButton").click(function() {
                var id = $(this).attr('data-id');
                $('.comment-div[data-id=' + id + ']').show(200);
                $(this).hide(200);
            });
            
            $(".cancelButton").click(function() {
                var id = $(this).attr('data-id');
                $('.comment-div[data-id=' + id + ']').hide(200);
                $('.commentButton[data-id=' + id + ']').show(200);
            });
            
            $(".postButton").click(function() {
                var id = $(this).attr('data-id');
                var author = $('.author[data-id=' + id + ']').val();
                var message = $('.message[data-id=' + id + ']').val();
                if(author!=="" && message!=="") {
                    $.ajax({
                        url: '/index/add-comment',
                        type: 'POST',
                        dataType: 'JSON',
                        data: {
                            author: author,
                            message: message,
                            id: id
                        },
                        success: function(json) {
                            $('.comment-div[data-id=' + id + ']').hide(200, function() {
                                $('.author[data-id=' + id + ']').val('');
                                $('.message[data-id=' + id + ']').val('');  
                            });
                            $('.commentButton[data-id=' + id + ']').show(200);
                            $('.comments[data-id=' + id + ']').prepend(json.html);
                        }
                    });
                }else {
                    alert('Remplissez tout les champs');
                }
            
            });
         </script>
         <hr>
         <footer>
            <p>&copy; 2010 - <?php echo date('Y') ?> by HE-Arc.</p>
         </footer>
      </div>
      <!-- /container -->
      <?php echo $this->inlineScript() ?>
   </body>
</html>
