            <form method="POST">
    <div class="form-group ">
        <label class="control-label"  for="inputTitle">Title</label>
        <input type="text" class="title form-control" id="inputTitle" name="title" placeholder="Title" value="">
    </div>
    <div class="form-group">
        <label class="control-label" for="inputDate">Date</label>
        <input type="date" class="date form-control" id="inputDate" name="date" placeholder="Date" value="2013-10-23">
    </div>
    <div class="form-group ">
        <label class="control-label" for="inputDescription">Description</label>
        <textarea class="description form-control" id="inputDescription" name="description" placeholder="Description" value=""></textarea>
    </div>
    <div style="text-align: right">
        <button class="cancelButton btn btn-default btn-sm">Cancel</button>
        <button type="submit" class="postButton btn btn-primary btn-sm">Publish</button>
    </div>
</form> 
