
<?php if ($this->message == 'error' || $this->message == 'notloggedin') {
    echo $this->headLink()
    ->prependStylesheet($this->basePath() . '/css/signin.css')
    ;
    ?>
    <div class="alert alert-danger"><?php echo ($this->message=='error') ? 'Wrong login information!' : 'You must login!';?></div>
    <form class="form-signin" method="post" action="<?php echo $this->url('home', array('action' => 'signin')); ?>">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="text" name="nickname" class="form-control" placeholder="Nickname" required autofocus>
        <input type="password" name="password" class="form-control" placeholder="Password" required>
        <label class="checkbox">
            <input type="checkbox" value="remember-me"> Remember me
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>

    </form>
    <?php } else {

    if ($this->message) {
        switch($this->message)
        {
            case "success":
            adminContent();
            break;
            case "notpermitted":
            ?><div class="alert alert-danger">You can't access this !</div><?php
            break;
        }
    }
} ?>

<?php
function adminContent() {

echo <<<END
<div class="row">

    <div class="col-md-6">

        <ul class="nav nav-tabs">
            <li class="active"><a href="#newSport" data-toggle="tab">New Sport</a></li>
            <li><a href="#newCourt" data-toggle="tab">New Court</a></li>
            <li><a href="#timetable" data-toggle="tab">Timetable</a></li>
        </ul>

        <div class="tab-content">
            <div class="tab-pane active" id="newSport">
                <div class="page-header">
                    <h1>New Sport <small>Form for add a new sport</small></h1>
                </div>
            </div>
            <div class="tab-pane" id="newCourt">
                <div class="page-header">
                    <h1>New Court <small>Form for add a new court</small></h1>
                </div>
            </div>
            <div class="tab-pane" id="timetable">
                <div class="page-header">
                    <h1>Timetable<small>Form to manage timetable</small></h1>
                </div>
            </div>
        </div>

    </div>

    <div class="col-md-6">
        <!-- Calendar here! -->
    </div>

</div>
END;
}
?>