
<?php if ($this->message == 'error' || $this->message == 'notloggedin') {
    echo $this->headLink()
    ->prependStylesheet($this->basePath() . '/css/signin.css')
    ;
    $this->headScript()->offsetSetFile(100, $basePath . '/js/jquery.min.js', 'text/javascript')
    ->offsetSetFile(101, $basePath . '/js/bootstrap.min.js');
    ?>
    <script type="text/javascript">
        window.onload() = function()
        {
            $('#example').tooltip(options);
            console.log("tits");
        };
    </script>
    <div class="alert alert-danger"><?php echo ($this->message=='error') ? 'Wrong login information!' : 'You must login!';?></div>
    <form class="form-signin" method="post" action="<?php echo $this->url('home', array('action' => 'signin')); ?>">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="text" name="nickname" class="form-control" placeholder="Nickname" required autofocus>
        <input type="password" name="password" class="form-control" placeholder="Password" required>
        <label class="checkbox">
            <input type="checkbox" value="remember-me"> Remember me
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>

    </form>
    <?php } else {

        //if ($this->message) {
        switch($this->message)
        {
            case "success":
            adminContent($this);
            break;
            case "notpermitted":
            ?><div class="alert alert-danger">You can't access this !</div><?php
            break;
            default:
            adminContent($this);
            break;
        }
            //}
    } ?>

    <?php

    function displayForm($form, $that) {
        foreach ($form as $element)
        {
            echo '<div class="form-group">';
            echo '<label class="col-md-3 control-label" for="'.$element->getAttribute('id').'">'.$element->getLabel().'</label>';
            echo '<div class="col-md-9">';
            echo $that->formElement($element);
            echo $that->formElementErrors()
                ->setMessageOpenFormat('<span class="label label-danger">')
                ->setMessageSeparatorString('</span><span class="label label-danger">')
                ->setMessageCloseString('</span>')
                ->render($element);
            echo '</div>';
            echo '</div>';
        }
    }

    function adminContent($that) {

        ?>
        <div class="row">

            <div class="col-md-6">

                <ul class="nav nav-tabs">
                    <li class="active"><a href="#sportCenter" data-toggle="tab">Sport Center</a></li>
                    <li><a href="#contact" data-toggle="tab">Contact page</a></li>
                    <li><a href="#users" data-toggle="tab">Users Managment</a></li>
                </ul>

                <div class="tab-content">
                    <div class="tab-pane active" id="sportCenter">
                        <h2>Sport Center</h2>
                        <form method="post">
                            <label>SportCenter name</label><input type="text" name="name1" class="form-control" /><br />
                            <label>SportCenter address</label><input type="text" name="name2" class="form-control" /><br />
                        </form>
                    </div>
                    <div class="tab-pane" id="contact">
                        <h2>Contact page</h2>
                    </div>
                    <div class="tab-pane" id="users">
                        <h2>Users Management</h2>
                    </div>
                </div>

                <ul class="nav nav-tabs">
                    <?php
                    $active = ' class="active"';
                    foreach ($that->sports as $sport) {
                        echo '<li'.$active.'>'.'<a href="#'.$sport->getName().'" data-toggle="tab">'.$sport->getName().'</a>'.'</li>';
                        $active = '';
                    }
                    echo '<li'.$active.'><a href="#newSport" data-toggle="tab"><span class="glyphicon glyphicon-plus"></span></a></li>';
                    $active = '';
                    ?>
                </ul>

                <div class="tab-content">
                    <?php
                    $active = ' active';
                    foreach ($that->sports as $sport) {
                        echo '<div class="tab-pane'.$active.'" id="'.$sport->getName().'">';
                        $active = '';

                    // Displaying courts
                        $courts = array_map(function($court) {
                            return array(
                                'id' => $court->getId(),
                                'name' => $court->getName(),
                                'description' => $court->getDescription(),
                                );
                        }, $sport->getCourts()->toArray());

                        echo '<div class="row">';

                        echo '<div class="col-md-3">';
                        echo '<h3>'.$sport->getName().'</h3>';
                        echo '<ul class="nav nav-pills nav-stacked">';
                        $active = ' class="active"';
                        foreach ($courts as $court) {
                            echo '<li'.$active.'>'.'<a href="#'.$court['name'].'" data-toggle="tab">'.$court['name'].'</a>'.'</li>';
                            $active = '';
                        }
                        echo '<li'.$active.'><a href="#newCourt'.$sport->getName().'" data-toggle="tab"><span class="glyphicon glyphicon-plus"></span></a></li>';
                        $active = '';
                        echo '</ul>';
                        echo '</div>';

                        echo '<div class="col-md-9">';
                        echo '<div class="tab-content">';
                        $active = ' active';
                        foreach ($courts as $court) {
                            echo '<div class="tab-pane'.$active.'" id="'.$court['name'].'">';
                            $active = '';
                            // Affichage des terrains.
                            $that->newCourtForm->setAttribute('class', 'form-horizontal');
                            $that->newCourtForm->get('id')->setAttribute('value', $court['id']);
                            $that->newCourtForm->get('name')->setAttribute('value', $court['name']);
                            $that->newCourtForm->get('description')->setAttribute('value', $court['description']);
                            $that->newCourtForm->get('sport')->setAttribute('value', $sport->getId());
                            $that->newCourtForm->get('newCourtSubmit')->setAttribute('name', 'modifyCourtSubmit');
                            $that->newCourtForm->get('newCourtSubmit')->setAttribute('value', 'Update');
                            $that->newCourtForm->prepare();
                            echo $that->form()->openTag($that->newCourtForm);
                            displayForm($that->newCourtForm, $that);
                            echo $that->form()->closeTag();
                            // Fin affichage des terrains.
                            echo '</div>';
                        }
                        echo '<div class="tab-pane'.$active.'" id="newCourt'.$sport->getName().'">';
                        $active = '';
                        echo '<h3>Add a new '.$sport->getName().' court</h3>';
                        $that->newCourtForm->setAttribute('class', 'form-horizontal');
                        $that->newCourtForm->get('id')->setAttribute('value', '');
                        $that->newCourtForm->get('name')->setAttribute('value', '');
                        $that->newCourtForm->get('description')->setAttribute('value', '');
                        $that->newCourtForm->get('sport')->setAttribute('value', $sport->getId());
                        $that->newCourtForm->get('newCourtSubmit')->setAttribute('name', 'newCourtSubmit');
                        $that->newCourtForm->get('newCourtSubmit')->setAttribute('value', 'New Court');
                        $that->newCourtForm->prepare();
                        echo $that->form()->openTag($that->newCourtForm);
                        displayForm($that->newCourtForm, $that);
                        echo $that->form()->closeTag();
                        echo '</div>';

                        echo '</div>';

                        echo '</div>';
                    //Displaying courts end

                        echo '</div>';
                        echo '</div>';
                    }
                    ?>
                    <div class="tab-pane<?php echo $active; ?>" id="newSport">
                        <h3>Add a new sport</h3>
                        <?php
                        $that->newSportForm->setAttribute('class', 'form-horizontal');
                        $that->newSportForm->prepare();
                        echo $that->form()->openTag($that->newSportForm);
                        displayForm($that->newSportForm, $that);
                        echo $that->form()->closeTag();
                        ?>
                    </div>
                </div>

            </div>

            <div class="col-md-6">
                <!-- Calendar here! -->
            </div>

        </div>
        <?php
    } ?>
