<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <?php foreach($this->posts as $post): ?>

        <div class="panel panel-default">
            <div class="panel-heading" style="min-height: 75px">
                <h3 class="panel-title">
                        <table class="date">
                            <tr>
                                <td rowspan="2" class="day"><?php echo $post->getDate()->format('d');?></td>
                                <td><?php echo $post->getDate()->format('M');?></td>
                            </tr>
                            <tr>
                                <td><?php echo $post->getDate()->format('Y');?></td>
                            </tr>
                        </table>
                        <div style="font-weight: bold;margin-left: 140px; line-height: 50px"><?php echo $post->getTitle();?></div>
                    </h3>
            </div>
            <div class="panel-body">
                <p>
                    <?php echo $post->getDescription();?></p>
            </div>
            <div class="panel-footer">
                <div class="comment-div" data-id="9" style="display: none">
                    <div class="form-group">
                        <label for="inputName">Nom</label>
                        <input type="text" data-id="9" class="author form-control" id="inputName" placeholder="Nom">
                    </div>
                    <div class="form-group">
                        <label for="inputMessage">Message</label>
                        <textarea class="message form-control" data-id="9" id="inputMessage" placeholder="Message"></textarea>
                    </div>
                    <div style="text-align: right">
                        <button class="cancelButton btn btn-default btn-sm" data-id="9">Cancel</button>
                        <button class="postButton btn btn-primary btn-sm" data-id="9">Post</button>
                    </div>
                </div>
                <div style="text-align: right; margin-bottom: 20px">
                    <button class="commentButton btn btn-default btn-sm" data-id="9">Comment</button>
                </div>
                <ul data-id="9" class="comments list-group" style="width: 100%">
                    <li class="list-group-item">
                        <div class="commentdate">23.10.2013 - 14:38:45</div>
                        <div class="author"><span>test</span> write :</div>
                        <div class="message">stest</div>
                    </li>
                    </table>

            </div>
        </div>


        <?php endforeach; ?>
    </div>
</div>
