
<?php if ($this->message == 'error') {
    echo $this->headLink()
    ->prependStylesheet($this->basePath() . '/css/signin.css')
    ;
    ?>
    <div class="alert alert-danger">Wrong log in information!</div>
    <form class="form-signin" method="post" action="<?php echo $this->url('home', array('action' => 'signin')); ?>">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="text" name="nickname" class="form-control" placeholder="Nickname" required autofocus>
        <input type="password" name="password" class="form-control" placeholder="Password" required>
        <label class="checkbox">
            <input type="checkbox" value="remember-me"> Remember me
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>

    </form>
    <?php } else {

    if ($this->message) {
        switch($this->message)
        {
            case "success":
            ?><div class="alert alert-success">Logged in !</div><?php
            break;
        }
    }
} ?>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/fr_FR/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="container">
    <?php echo $this->content; ?>
    <hr />
    <div>
        <p class="text-left"><?php
        echo $sportCenter->getName();
        echo ", ";
        ?> 
        </p>
        <p class="text-left"><?php
        echo $sportCenter->getPostCode();
        echo " ";
        echo $sportCenter->getCity();
        ?> 
        </p>
        <p class="text-left">
        <?php 
        echo $sportCenter->getAddress();
        ?>
        <p/>
        <p class="text-left">
        <?php 
        echo $sportCenter->getPhone();
        ?>
        <p/>
        <p>
        <a href="https://twitter.com/<?php echo $sportCenter->getTwitter();?>" class="twitter-follow-button" data-show-count="false" data-lang="fr">Suivre <?php echo $sportCenter->getTwitter ?></a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
        <div class="fb-like" data-href="https://www.facebook.com/<?php echo $sportCenter->getFacebook();?>" data-width="20" data-layout="button" data-action="like" data-show-faces="false" data-share="false"></div>
        <p/>



    </div>
</div>