
<?php if ($this->message == 'error') {
    echo $this->headLink()
    ->prependStylesheet($this->basePath() . '/css/signin.css')
    ;
    ?>
    <div class="alert alert-danger">Wrong log in information!</div>
    <form class="form-signin" method="post" action="<?php echo $this->url('home', array('action' => 'signin')); ?>">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="text" name="nickname" class="form-control" placeholder="Nickname" required autofocus>
        <input type="password" name="password" class="form-control" placeholder="Password" required>
        <label class="checkbox">
            <input type="checkbox" value="remember-me"> Remember me
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>

    </form>
    <?php } else {

    if ($this->message) {
        switch($this->message)
        {
            case "success":
            ?><div class="alert alert-success">Logged in !</div><?php
            break;
        }
    }
} ?>

<?php

$geocodeURL = "http://maps.googleapis.com/maps/api/geocode/json?address=".$sportCenter->getPostCode()."+".$sportCenter->getCity()."+".str_replace(' ', '', $sportCenter->getAddress())."&sensor=false";

$json = file_get_contents($geocodeURL);
$json = json_decode($json);

$lat = $json->{'results'}[0]->{'geometry'}->{'location'}->{'lat'};
$lng = $json->{'results'}[0]->{'geometry'}->{'location'}->{'lng'};

?>

        <style>
            #map_canvas {
            width: 500px;
            height: 400px;
            }
        </style>
        <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
        <script>
            function initialize() {

                var map_canvas = document.getElementById('map_canvas');
                var map_options = {
                    center: new google.maps.LatLng(<?php Print($lat); ?>,<?php Print($lng); ?>),
                    zoom: 14,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                }
                var map = new google.maps.Map(map_canvas, map_options)
            }
        google.maps.event.addDomListener(window, 'load', initialize);
        </script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/fr_FR/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="container">
    <?php echo $this->content; ?>
    <hr />
    <div class="panel panel-info">
        <div class="panel-heading"><h3>Comment nous contacter?</h3></div>
        <p class="text-left"><?php
        echo "<h4>";
        echo $sportCenter->getName();
        echo "</h4>";
        ?> 
        </p>
        <p class="text-left"><?php

        echo "<h4>";
        echo $sportCenter->getPostCode();
        echo " ";
        echo $sportCenter->getCity();
        echo "</h4>";
        ?> 
        </p>
        <p class="text-left">
        <?php 
        echo "<h4>";
        echo $sportCenter->getAddress();
        echo "</h4>";
        ?>
        <p/>
        <p class="text-left">
        <?php 
        echo "<h4>";
        echo "Téléphone: ";
        echo $sportCenter->getPhone();
        echo "</h4>";
        ?>
        <p/>
        <p>
        <a href="https://twitter.com/<?php echo $sportCenter->getTwitter();?>" class="twitter-follow-button" data-show-count="false" data-lang="fr">Suivre <?php echo $sportCenter->getTwitter ?></a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
        <div class="fb-like" data-href="https://www.facebook.com/<?php echo $sportCenter->getFacebook();?>" data-width="20" data-layout="button" data-action="like" data-show-faces="false" data-share="false"></div>
        <p/>


        <div id="map_canvas"></div>



    </div>
</div>