<div class="row">
    <table border = "1">
        <tr>
            <td>
                <table>
                    <tr>
                        <td>
                            1
                        </td>
                    </tr>
                    <tr>
                        <td>
                            2
                        </td>
                    </tr>
                </table>
            </td>
            <td>
                <img src="img/pic.png" alt="some_text" height="400" width="500">
            </td>
        </tr>
    </table>
</div>
