<div class="row">
    <div class="span12">
	<?php
		$form->setAttribute('class', 'form-horizontal');
		$form->prepare();
		
		echo $this->form()->openTag($form);
		
		foreach ($form as $element)
		{
			echo '<div class="form-group">';
			echo '<label class="col-sm-2 control-label" for="'.$element->getAttribute('id').'">'.$element->getLabel().'</label>';
			echo '<div class="col-sm-6">';
			echo $this->formElement($element);
			// echo $this->formElementErrors($element);
			echo $this->formElementErrors()
				->setMessageOpenFormat('<span class="label label-danger">')
				->setMessageSeparatorString('</span><span class="label label-danger">')
				->setMessageCloseString('</span>')
				->render($element);
			echo '</div>';
			echo '</div>';
		}
		
		echo $this->form()->closeTag();
	?>
    </div>
</div>


<!-- <div class="container-fluid">
	<div class="row-fluid">
		<?php
		echo $this->form()->openTag($form);
		echo $this->formCollection($form);
		echo $this->form()->closeTag();

		?>
	</div>
</div> -->
